# Generated by Django 5.0.6 on 2024-08-05 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_prevvote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrevVote',
        ),
    ]
